### PR TITLE
Add more language components

### LINKED ISSUE #137: More language components needed
In the website, there are is Language dropdown menu in the header/navbar.
Add more languages that are not yet in this list. The Language components has to be made similarly as the other components, so you can simply copypaste existing language component inside `components/languageComponents` directory and create new component from that by adding the information needed as well as the badge image if it is available. 

After creating the component:
-   Add the path to `data/languageList.ts` file similarly as the other paths.
-   Add the component inside `pages/languages/[lang].tsx` file same way as the other components are added.

Remember to ask permission to get signed for this task to avoid other contributors possible working at the same issue and avoiding conflicts.

Feel free to ask any questions here if you have some problems!

### PR DESCRIPTION
**Pull request by arbiasgjoshi**
This PR fixes #137 by adding two more languages to the existing languages list, in the header navbar to solve this issue: 

While following the guidelines I've made the following changes: 

- Created two new languages, `YAML` and `ZSH`
- Said languages have been added to the `data/languageList.ts`
- Component files, have then also been added to the `pages/languages/[lang].tsx`
- Followed the appropriate linting guidelines. 
- Tested the addition of said languages on the front side, and they appear as intended. 

Let me know if more languages are required.

### CODE REVIEW

**Comment by nikohoffren** [comment]
> This PR fixes #137 by adding two more languages to the existing languages list, in the header navbar to solve this issue:
> 
> While following the guidelines I've made the following changes:
> 
>     * Created two new languages, `YAML` and `ZSH`
> 
>     * Said languages have been added to the `data/languageList.ts`
> 
>     * Component files, have then also been added to the `pages/languages/[lang].tsx`
> 
>     * Followed the appropriate linting guidelines.
> 
>     * Tested the addition of said languages on the front side, and they appear as intended.
> 
> 
> Let me know if more languages are required.

Looks good, i'm happy with those changes!

I think YAML and ZSH is fine for now. If you want to add more languages or frameworks to this website in the future, feel free to make new PR.

**Review by nikohoffren — APPROVED** [review]

**Comment by nikohoffren** [comment]
## Pull request merged

> This is an automated message from Fork, Commit, Merge - web [BOT].

Thank you for your contribution! Your pull request has been merged and your name has been added to the List of Contributors in README.md.
Please leave a star if you enjoyed working on this project.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects [here](https://github.com/nikohoffren?tab=repositories).

**Comment by arbiasgjoshi** [comment]
@nikohoffren I attempted to find the most relative ones, and those two stood out as the most obvious ones, but over the weekend I will be checking for others, and see what I can add as further improvements.

**Comment by nikohoffren** [comment]
> @nikohoffren I attempted to find the most relative ones, and those two stood out as the most obvious ones, but over the weekend I will be checking for others, and see what I can add as further improvements.

Sounds good!

**Pull request merged**
